language: java

branches:
  only:
    - master

jdk:
  - openjdk11
  - oraclejdk11

notifications:
  email: true

addons:
  sonarcloud:
    organization: "malkomich-github"
    token: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
